services:
  postgres_vertical:
    container_name: postgres_api_luizalabs
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"